package com.iosix.eldblesample.utils;

public class Constants {
    public static final String CHANNEL_ID = "foregroundServiceChannel";

    public static final String[] unitDefects = {
            "Air Compressor",
            "Air Lines",
            "Battery",
            "Body",
            "Brake Accessories",
            "Brakes, Parking",
            "Brakes, Service",
            "Clutch",
            "Coupling Devices",
            "Defroster/ Heater",
            "Drive Line",
            "Engine",
            "Exhaust",
            "Fifth Wheel",
            "Frame and Assembly",
            "Front Axle",
            "Fuel Tanks",
            "Horn",
            "Lights(Head- Stop)",
            "Lights(Tail- Dash)",
            "Lights(Turn Indicators)",
            "Mirrors",
            "Muffler",
            "Oil Pressure",
            "Radiator",
            "Rear End",
            "Refresh",
            "Safety Equipment(Fire Extinguisher)",
            "Safety Equipment(Reflective Triangles)",
            "Safety Equipment(Flag - Flares- Fusses)",
            "Safety Equipment(Spare Bulbs & Fuses)",
            "Safety Equipment(Spare Seal Beam)",
            "Suspension System",
            "Starter",
            "Steering",
            "Tachograph",
            "Tires",
            "Tire Chains",
            "Transmission",
            "Wheels and Rims",
            "Windows",
            "Windshield Wipers",
            "Other",
    };

    public static final String[] trailerDefects = {
            "Frame and Assembly",
            "Front Axle",
            "Fuel Tanks",
            "Horn",
            "Lights(Head- Stop)",
            "Lights(Tail- Dash)",
            "Lights(Turn Indicators)",
            "Mirrors",
            "Muffler",
            "Oil Pressure",
            "Radiator",
            "Rear End",
            "Refresh",
            "Safety Equipment(Fire Extinguisher)",
            "Safety Equipment(Reflective Triangles)",
            "Safety Equipment(Flag - Flares- Fusses)",
            "Safety Equipment(Spare Bulbs & Fuses)",
            "Safety Equipment(Spare Seal Beam)",
            "Suspension System",
            "Starter",
            "Steering",
            "Tachograph",
            "Other",
    };
}
